Doobie draft copy pending debugging
JoseUtrilla-MBA/PlayFramework_RestAPI_Practice pull request #1
Opened 2021-06-02 18:08 UTC by JoseUtrilla-MBA

Hi Juan,
This commit is realy a draft pending to debugging. It works, but not well, and source must be cleaned. 
Database is yet local, so it's pending to use docker-postgres.

It's a fisrt approach to test Doobie.

2021-07-14 16:40 UTC, vejeta commented on app/v1/product/data/Connection.scala
> +    "postgres", // user
We might still want to read the values from the configuration.
We can use https://www.playframework.com/documentation/2.0/api/java/play/Configuration.html

in a first approach.

2021-07-14 16:42 UTC, vejeta requested changes

2021-07-14 16:42 UTC, vejeta commented on app/v1/product/data/Connection.scala
> +      "admin", // password
We should read these values from application.conf, 
remember that their values can also be obtained from environment variables.

To read the values from application.conf, play config library can be used to start with:

https://www.playframework.com/documentation/2.0/api/java/play/Configuration.html

2021-07-14 17:01 UTC, JoseUtrilla-MBA commented on app/v1/product/data/Connection.scala
> +      "admin", // password
I just did commit within several modifications, but it created a new PR. I thought that if I make a commit to the same branch, this commit will be added to the currently open PR ...

2021-07-14 17:13 UTC, JoseUtrilla-MBA commented on app/v1/product/data/Connection.scala
> +      "admin", // password
I just realized that I have used the workbranchII branch again, can I remove the previous PR and keep this last?

2021-07-16 19:34 UTC, bilki reviewed
Try to keep things a bit more organized: create packages for controllers, services, repositories, models... I think you are also overengineering your product controller, using that `ProductionActionBuilder`, `ProductControllerComponents`, etc. That only adds more complexity in my opinion. Stick to the simple controller from Play docs.

2021-07-16 19:34 UTC, bilki commented on app/v1/product/ProductController.scala
> +  def process: Action[AnyContent] = ProductAction.async { implicit request =>
I don't get why are you processing the request body as a form here, isn't the idea is to parse it as a JSON? :thinking:

2021-07-16 19:34 UTC, bilki commented on app/v1/product/ProductResourceHandler.scala
> +class ProductResourceHandler @Inject()(manageTypeProduct: ManageTypeProduct, productRepository: ProductRepository)(implicit ec: ExecutionContext) {
This looks more like a service than a "handler" to me.

2021-07-16 19:34 UTC, bilki commented on app/v1/product/ProductResourceHandler.scala
>    private def createProductResource(p: ProductData): ProductResource = {
This function name is a bit misleading, maybe you want to rename it to `fromData` and move it to the `ProductResource` companion object.

2021-07-16 19:34 UTC, bilki commented on app/v1/product/ProductResourceHandler.scala
> +    ProductResource(p.id, manageTypeProduct.get(p.id_typeProduct).name, p.name, p.gender, p.size, p.price)
That `manageTypeProduct.get` is also too much confusing. Isn't it a repository? Name it as such, and move the `get` outside this function, you don't want unexpected side effects inside a function as simple as this one.

2021-07-16 19:34 UTC, bilki commented on app/v1/product/ProductResourceHandler.scala
> +  def remove(id: String)(implicit mc: MarkerContext): Future[Iterable[ProductResource]] = try {
Do not use `try-catch`, there are functions in `Future` like `recover` and `recoverWith` to deal with failures.

2021-07-16 19:34 UTC, bilki commented on app/v1/product/data/ProductRepository.scala
> +case class ManageTypeProduct @Inject()(connection: Connection) {
This is a repository in disguise, name it as such, something like `ProductTypeRepository`.

2021-07-16 19:34 UTC, bilki commented on app/v1/product/data/ProductRepository.scala
> +      connection.transactor.use(productList.transact[IO]).unsafeRunSync()
Get rid of that `Future` blocks.

```suggestion
      connection.transactor.use(productList.transact[IO]).unsafeToFuture()
```

2021-07-16 19:34 UTC, bilki commented on app/v1/product/data/ProductRepository.scala
> +      connection.transactor.use(productList.transact[IO]).unsafeRunSync()
This could be rewritten as a for comprehension. Check the examples from doobie docs.

2021-07-16 19:34 UTC, bilki commented on test/PostRouterSpec.scala
> +class PostRouterSpec extends PlaySpec with GuiceOneAppPerTest {
These tests do not work without a postgres instance running locally. Take a look at testcontainers https://github.com/testcontainers/testcontainers-scala instead.

2021-07-16 19:34 UTC, bilki commented on app/v1/product/data/ProductRepository.scala
> +  def delete(id: Int)(implicit mc: MarkerContext): Future[Iterable[ProductData]]
I'd choose `List` or `Seq` instead of `Iterable`.

2021-07-16 19:34 UTC, bilki commented on app/v1/product/ProductController.scala
> +        "id_typeProduct" -> of[Int],
This is a weird mix of snake case and camel case. Stick to snake case for input form fields, and camel case for case class constructor arguments.

2021-07-18 18:06 UTC, JoseUtrilla-MBA commented on app/v1/product/ProductResourceHandler.scala
> +class ProductResourceHandler @Inject()(manageTypeProduct: ManageTypeProduct, productRepository: ProductRepository)(implicit ec: ExecutionContext) {
> Try to keep things a bit more organized: create packages for controllers, services, repositories, models... I think you are also overengineering your product controller, using that `ProductionActionBuilder`, `ProductControllerComponents`, etc. That only adds more complexity in my opinion. Stick to the simple controller from Play docs.

Hi Roberto,
I have a question about your comment referring to 'stick to the simple controller from play docs', if I check the Play documentation, the standard controller is sequential (it doesn't work whith future), you refer to that?

2021-07-18 20:31 UTC, vejeta commented on app/v1/product/ProductResourceHandler.scala
> +class ProductResourceHandler @Inject()(manageTypeProduct: ManageTypeProduct, productRepository: ProductRepository)(implicit ec: ExecutionContext) {
Usually in play, things are organized in:

* controllers (the methods that receive the call from the REST API routes). They contain little logic
* services: They contain more logic and can call repositories to fetch data from databases, or call other clients.

I think that @bilki refers that this ProductResourceHandler could be renamed into a package called "services" and the name of the class be renamed to ProductService for example.

Please, @bilki, confirm.

2021-07-18 21:33 UTC, JoseUtrilla-MBA commented on app/v1/product/ProductResourceHandler.scala
> +class ProductResourceHandler @Inject()(manageTypeProduct: ManageTypeProduct, productRepository: ProductRepository)(implicit ec: ExecutionContext) {
Sorry, I did somethig wrong because my question wasn't refering to this comment, I just referred to the initial comment where you write: 'overengineering the product controller... Stick to the simple controller from Play docs'.
However, this comment about the concepts of service o handler, is another question where I have looked for documentation but it has not been clear to me, I don't really know what is the difference between them.

Thank you Juan!!!

2021-07-18 23:40 UTC, JoseUtrilla-MBA commented on app/v1/product/data/ProductRepository.scala
> +      connection.transactor.use(productList.transact[IO]).unsafeRunSync()
for every method from trait ProductRepository??

2021-07-19 15:52 UTC, JoseUtrilla-MBA commented on app/v1/product/ProductController.scala
> +  def process: Action[AnyContent] = ProductAction.async { implicit request =>
working on it

2021-07-19 15:54 UTC, JoseUtrilla-MBA commented on app/v1/product/ProductResourceHandler.scala
> +class ProductResourceHandler @Inject()(manageTypeProduct: ManageTypeProduct, productRepository: ProductRepository)(implicit ec: ExecutionContext) {
Package and class name changed in commit fe8a098

2021-07-19 16:00 UTC, JoseUtrilla-MBA commented on app/v1/product/ProductResourceHandler.scala
>    private def createProductResource(p: ProductData): ProductResource = {
working on it. 
I can't nest entities that depend on each other, using foreign key in database

2021-07-19 16:01 UTC, JoseUtrilla-MBA commented on app/v1/product/ProductResourceHandler.scala
> +    ProductResource(p.id, manageTypeProduct.get(p.id_typeProduct).name, p.name, p.gender, p.size, p.price)
done in commit fe8a098

2021-07-19 16:02 UTC, JoseUtrilla-MBA commented on app/v1/product/ProductResourceHandler.scala
> +  def remove(id: String)(implicit mc: MarkerContext): Future[Iterable[ProductResource]] = try {
done in commit fe8a098

2021-07-19 16:02 UTC, JoseUtrilla-MBA commented on app/v1/product/data/ProductRepository.scala
> +case class ManageTypeProduct @Inject()(connection: Connection) {
done in commit fe8a098

2021-07-19 16:03 UTC, JoseUtrilla-MBA commented on app/v1/product/data/ProductRepository.scala
> +      connection.transactor.use(productList.transact[IO]).unsafeRunSync()
done in commit fe8a098

2021-07-19 16:03 UTC, JoseUtrilla-MBA commented on app/v1/product/data/ProductRepository.scala
> +  def delete(id: Int)(implicit mc: MarkerContext): Future[Iterable[ProductData]]
done in commit fe8a098

2021-07-21 21:13 UTC, JoseUtrilla-MBA commented on app/v1/product/ProductController.scala
> +  def process: Action[AnyContent] = ProductAction.async { implicit request =>
Done in commit 5066f31

2021-07-21 21:13 UTC, JoseUtrilla-MBA commented on app/v1/product/ProductResourceHandler.scala
>    private def createProductResource(p: ProductData): ProductResource = {
Done in commit 5066f31

2021-07-21 21:14 UTC, JoseUtrilla-MBA commented on app/v1/product/ProductController.scala
> +        "id_typeProduct" -> of[Int],
Done in commit 5066f31

2021-07-28 13:11 UTC, vejeta commented on app/v1/product/data/ProductRepository.scala
> +      connection.transactor.use(productList.transact[IO]).unsafeRunSync()
@vejeta Now, I understand what you asked about Roberto's request.
It is unnecessary to put the result inside an artificially created Future{}

So, just need to leave the code outside of the Future block, removing the Future.


A question for @bilki, is it a common pattern to use unsafeRunSync() on this layer?

2021-08-04 23:43 UTC, vejeta requested changes

2021-08-11 14:41 UTC, vejeta approved these changes

2021-08-11 22:44 UTC, merged